services:

  mongodb:
    image: mongo:8
    container_name: expense-tracker-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  temporal-postgresql:
    image: postgres:16
    container_name: expense-tracker-temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5432:5432"
    volumes:
      - temporal_postgresql_data:/var/lib/postgresql/data

  temporal:
    image: temporalio/auto-setup:1.29.1
    container_name: expense-tracker-temporal
    depends_on:
      - temporal-postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "7233:7233"

  temporal-ui:
    image: temporalio/ui:2.34.0
    container_name: expense-tracker-temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8080:8080"

volumes:

  mongodb_data:

  temporal_postgresql_data: